In [2]:
import numpy as np

In [3]:
x = np.array([[1,2,3], [4,5,6]])

In [4]:
print (x)

[[1 2 3]
 [4 5 6]]


In [5]:
print ("x: ",  x)

x:  [[1 2 3]
 [4 5 6]]


In [6]:
from scipy import sparse

# Create a 2D NumPy array with a diagonal of ones, and zeros everywhere else
eye = np.eye(4)
print("NumPy array:\n{}".format(eye))


NumPy array:
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [7]:
# Convert the NumPy array to a SciPy sparse matrix in CSR format
# Only the nonzero entries are stored
sparse_matrix = sparse.csr_matrix(eye)
print("\nSciPy sparse CSR matrix:\n{}".format(sparse_matrix))

# This prints a f R2 --> R function.

 


SciPy sparse CSR matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [8]:
data = np.ones(6)
x = np.arange(6)
y = np.arange(6)

eye_coo = sparse.coo_matrix((data, (x, y)))


In [9]:
print ("A 6x6 Square Identity Matrix:", "\n", eye_coo)


A 6x6 Square Identity Matrix: 
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0
  (5, 5)	1.0
